name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: |
          npm run format:check
          cargo fmt -- --check

      - name: Lint TypeScript
        run: npm run lint

      - name: Lint Rust
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: |
          npm test
          cargo test 